version: '3'

# Define the services/containers to be run
services:
  myapp: #name of your service
    build: ./ # specify the directory of the Dockerfile
    command: nodemon -L --inspect=0.0.0.0:5858
    ports:
      - "3000:3000" #specify ports forwarding
      - "5858:5858"
    environment:
      -  NODE_ENV=dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      
  database: # name of the service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: